ALTER TYPE "DeclarationType" ADD VALUE IF NOT EXISTS 'EXPIRY_DATE';
ALTER TYPE "DeclarationType" ADD VALUE IF NOT EXISTS 'BATCH_NUMBER';
ALTER TYPE "DeclarationType" ADD VALUE IF NOT EXISTS 'FSSAI_NUMBER';